### ISSUE TITLE
More explanation

### ISSUE THREAD

**Issue by venkisagunner93** [mvallim/live-custom-ubuntu-from-scratch#12]
Thank you for the work. I'm using your repository to create my own boot to RAM flavor. 

Just wanted to get some more clarification on some of the commands. At the very end you are using `grub-mkstandalone` to create BIOS and UEFI image (I dont know the difference). My question is if I'm trying to partition using GPT is it enough to create only UEFI image? If so how would I modify `xorriso` command ? Thank you help much appreciated.

```
grub-mkstandalone \
   --format=x86_64-efi \
   --output=isolinux/bootx64.efi \
   --locales="" \
   --fonts="" \
   "boot/grub/grub.cfg=isolinux/grub.cfg"

sudo xorriso \
   -as mkisofs \
   -iso-level 3 \
   -full-iso9660-filenames \
   -volid "Ubuntu from scratch" \
   -eltorito-boot boot/grub/bios.img \
   -no-emul-boot \
   -boot-load-size 4 \
   -boot-info-table \
   --eltorito-catalog boot/grub/boot.cat \
   --grub2-boot-info \
   --grub2-mbr /usr/lib/grub/i386-pc/boot_hybrid.img \
   -eltorito-alt-boot \
   -e EFI/efiboot.img \
   -no-emul-boot \
   -append_partition 2 0xef isolinux/efiboot.img \
   -output "../ubuntu-from-scratch.iso" \
   -m "isolinux/efiboot.img" \
   -m "isolinux/bios.img" \
   -graft-points \
      "/EFI/efiboot.img=isolinux/efiboot.img" \
      "/boot/grub/bios.img=isolinux/bios.img" \
      "."
```

**Comment by mvallim** [comment]
Hi @venkisagunner93 ,

Do you check that https://github.com/mvallim/live-custom-ubuntu-from-scratch#alternative-way-if-previous-one-fails-create-an-hybrid-iso?

Thanks,
