### ISSUE TITLE
Add boot loaders for both BIOS and UEFI mode

### ISSUE THREAD

**Issue by mki77** [mvallim/live-custom-ubuntu-from-scratch#14]
See https://github.com/mvallim/live-custom-ubuntu-from-scratch/pull/17

**Comment by fcore117** [comment]
Hello, could you be kind to reconfigure your fixes against this ubuntu plan so there is less confusion. Currently it wont exactly match to Ubuntu series.

I still try to make my own build plan based on this repo and i still have random various issues still. I want to build my plan so i can easily as possible to move forward with future Ubuntu versions. Currently i target 21.04 to be as barebone plain desktop with some apps.

[Ubuntu 21.04 still with random issues.zip](https://github.com/mvallim/live-custom-ubuntu-from-scratch/files/5888730/Ubuntu.21.04.still.with.random.issues.zip)

**Comment by fcore117** [comment]
Thanks, but any idea what could be that critical package that is missed with no-recommends? i for example do not want that any help or slideshow to be pulled and no fonts(without no-recommends enabled there comes tons of African, Chinese etc.. fonts i do not need), no manuals and other stuff that is chained with packages.

**Comment by mki77** [comment]
Nobody know what might be missing, try the apt command with and without the recommendations, then stop it and remove only known apps and fonts from list.

**Comment by fcore117** [comment]
Thanks, yes i continue my trials as long as needed to find these culprit packages that breaks installer installing sometimes. Good night/day :)

**Comment by mki77** [comment]
I've written a script where you can use Synaptic, it could be simpler:
https://github.com/mvallim/live-custom-ubuntu-from-scratch/issues/15

**Comment by mvallim** [comment]
Hi @mki77,

Could you open a Pull Request for this?

Thanks for you contribution.

**Comment by mki77** [comment]
Yes, it will be done.
