### ISSUE TITLE
Hint: An easy building script

### ISSUE THREAD

**Issue by mki77** [mvallim/live-custom-ubuntu-from-scratch#15]
See pull request https://github.com/mvallim/live-custom-ubuntu-from-scratch/pull/16

**Comment by mvallim** [comment]
Hi @mki77,

Do you check this scripts https://github.com/mvallim/live-custom-ubuntu-from-scratch/tree/master/scripts?

Thanks for you contribution.

**Comment by mki77** [comment]
Yes, I've seen your scripts, but there are no instructions and they don't fit different needs without modification. I wanted to provide a generic script that anyone can use without studying bash. I've also added an X session for Synaptic usage. Give us a look.

**Comment by mvallim** [comment]
Merger PR #16
