### ISSUE TITLE
Produced ISO fails to install in Virtualbox

### ISSUE THREAD

**Issue by kgilmer** [mvallim/live-custom-ubuntu-from-scratch#19]
Steps to reproduce:
1. create docker instance w/ Ubuntu 20.04
2. run README steps in docker container to produce `ubuntu-from-scratch.iso`
3. create new VM in VirtualBox, attach `ubuntu-from-scratch.iso` as secondary volume
4. boot live environment, select "Install Ubuntu" from the GRUB menu
5. Go through the installation steps, select minimal install and download packages while installing.

Expected behavior:
Ubuntu installation process completes successfully

Actual behavior:
After package install completes and cleanup scripts are run, the following error is shown:

![VirtualBox_lbtest_05_04_2021_17_11_49](https://user-images.githubusercontent.com/49683/113641531-a8d51480-9632-11eb-95cb-1fa8c5a2a116.png)

Note: Removing secondary image and rebooting the VirtualBox image results in booting into grub with just the prompt, no selectable boot configurations:

![VirtualBox_lbtest_05_04_2021_17_17_30](https://user-images.githubusercontent.com/49683/113641617-dde16700-9632-11eb-9f0f-eba17546d736.png)

**Comment by mvallim** [comment]
Hi @kgilmer,

I identified the problem, it was missing the installation of `sudo` as part of the" active system "and as a standard part of the OS installation.

You can see this in: **"Install packages needed for Live System"**

Thank you for reporting a bug.

**Comment by kgilmer** [comment]
@mvallim , fix verified and **THANK YOU SO MUCH**!  I have spent a long time trying to find a way to generate Ubuntu ISO installers in a simple, automated way.

If I end up using your project to make mine, how would you prefer to be credited?  By your github alias, the repo name, or something else?

Thanks again!

**Comment by mvallim** [comment]
Hi @kgilmer,

Thank you for feedback.

Just referencing the repository is enough.

Thank you again. 😄
