### ISSUE TITLE
Boot from Pen Drive

### ISSUE THREAD

**Issue by tejinderkang** [mvallim/live-custom-ubuntu-from-scratch#2]
Hello Vallim,
Thanks, This is working fine with ISO image and I'm able to boot Ubuntu with Ubuntu Custom ISO.
But when I create a bootable pen drive from Custom ISO then it doesn't work.
I'm using the tool Rufus-3.8 to create a bootable pen drive from Custom ISO.

Kindly help me to create a bootable pen drive from Ubuntu Custom ISO. 

Regards,
Tejinder

**Comment by mvallim** [comment]
Hello Tejinder,
Thanks for the feedback.
I need more information about the problem you are facing so that I can help you.

The tests done here using `dd` or` gnome-disks` work for both UEFI and Legacy boot using a USB stick.

```
sudo dd if=ubuntu-from-scratch.iso of=/dev/sde status=progress oflag=sync
```

Could you inform me in more detail about the problem you are encountering?

Regards,
Vallim

**Comment by tejinderkang** [comment]
Hello Vallim,
Thanks for reply,,

I have try both command below given, but no luck.    
#sudo dd if=ubuntu-from-scratch.iso of=<device> bs=4M
#sudo dd if=ubuntu-from-scratch.iso of=<device> status=progress oflag=sync

By executing the above command, pen drive successfully created, but when to try to boot from pen drive it shows the following error on boot.

error: no such device: /ubuntu
error: file '/casper/vmlinuz' not found.
alloc magic is broken at 0xcaf02420: cad71880
Aborted. Press any key to exit. 

Regards,
Tejinder

**Comment by mvallim** [comment]
Hi @tejinderkang,

Could you provide the ISO you generate somewhere I can download and analyze the generated image? (DropBox, etc)

Regards,

**Comment by tejinderkang** [comment]
Hello Vallim,

The issue has been resolved now. Actually there is an issue in Pen Drive. I have tested with other Pen drive and its working fine.

Thanks for the support.

Regards,
Tejinder

**Comment by mvallim** [comment]
Nice,

Thanks for all.

Regards,
