### ISSUE TITLE
is:open label:question Ubuntu 20.04

### ISSUE THREAD

**Issue by LuceCompany** [mvallim/live-custom-ubuntu-from-scratch#3]
Do you planning version for Ubuntu 20.04 ?
I change archive from bionic on focal. Other steps in this same way but when I boot ISO Image, then bootloader find one error. I dont kwno how check what it is bad in ISO. Have you maybe any idea? I dont installed any optional packages.

**Comment by mvallim** [comment]
@LuceCompany,

I'm working on updating this how to to the Focal Fossa version.

**Comment by mvallim** [comment]
Hi @LuceCompany,

The new version of "Como" was released, with checksum correction for the files on the boot CD.

Thanks for everything,
