### ISSUE TITLE
Failure to install on actual PC using EFI

### ISSUE THREAD

**Issue by kgilmer** [mvallim/live-custom-ubuntu-from-scratch#30]
**Describe the bug**
When installing ubuntu-from-scratch.iso into a virtualbox there is no problem, however when installing into a regular PC, at the end of the installation process I see a dialog with the error starting with "grub-efi-amd64-signed’ package failed to install..."  and from this point the installation exits.

I have reproduced the problem on two computers, 1 laptop and 1 desktop PC.
I have reproduced the problem with both "secure boot" enabled ~~and disabled in the BIOS.~~ (the problem does not occur in "legacy mode")
I have reproduced the problem with the latest scripts and at commit `cf054a6c9503a021c8ccb8eb0d8207265e564e3c` (the last update before script refactoring)

**To Reproduce**
1.Build ISO, write to USB w/ dd
2. select Install Ubuntu from Scratch
3. go through installation process

**Expected behavior**
installation completes successfully

**Additional context**
After the failure I checked in `/var/log` for details regarding the error but didn't find anything.

**Comment by kgilmer** [comment]
Possibly related: https://forums.linuxmint.com/viewtopic.php?t=316278

**Comment by kgilmer** [comment]
Related: https://wiki.ubuntu.com/UEFI/SecureBoot

**Comment by kgilmer** [comment]
This issue (error dialog during install time) is resolved by adding the package `grub-efi`.

**Comment by kgilmer** [comment]
Reopening for PR

**Comment by sguazt** [comment]
Hello,

Thank you for this wonderful project.
I have troubles running the live image on a system with Secure Boot enabled. The live system simply does not boot.

Any idea on how to solve this issue?
Thanks.
