### ISSUE TITLE
Step 9 - not automatically launching grub

### ISSUE THREAD

**Issue by aggietallboy** [mvallim/live-custom-ubuntu-from-scratch#33]
Step 9 - Install packages needed for Live System
I copy/paste the command, but the grub installer does not launch (20.04 source) after running.

Not sure if there's a typo or something i missed

**Comment by mvallim** [comment]
Hi @aggietallboy,

I've made some fixes to the documentation and imaging scripts.

Could you check if everything is OK?

Thank you very much,
