### ISSUE TITLE
Conflicting licensing statements

### ISSUE THREAD

**Issue by Granddave** [mvallim/live-custom-ubuntu-from-scratch#37]
Hello, I noticed that which license the project is licensed under is ambiguous.

Namely, the [README.md](https://github.com/mvallim/live-custom-ubuntu-from-scratch/blob/master/README.md?plain=1#L760) states that the project is licensed under the Apache license and refers to the [LICENSE file](https://github.com/mvallim/live-custom-ubuntu-from-scratch/blob/master/LICENSE) that contains the GNU GPLv3.0 license. :)

**Comment by mvallim** [comment]
Fixed!

Thanks!
