### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by beacon-hash** [mvallim/live-custom-ubuntu-from-scratch#42]
How the kernel know the location of the root file system? I mean, in case of Linux installed on a hard drive, there's entry in the kernel command line that specify the root partition. But, for LiveCD I don't know where I should configure that. When I customize a LiveCD image, I get stuck at initramfs command line and the error "Can't find the root file system". Should I configure that in the initrd image itself? and how?

**Comment by mvallim** [comment]
> How the kernel know the location of the root file system? I mean, in case of Linux installed on a hard drive, there's entry in the kernel command line that specify the root partition. But, for LiveCD I don't know where I should configure that. When I customize a LiveCD image, I get stuck at initramfs command line and the error "Can't find the root file system". Should I configure that in the initrd image itself? and how?

Hello @beacon-hash,

Using the step-by-step guide, when you enter the chroot, you execute all the necessary procedures you want to customize. After you've done what you need, there is a step that copies the vmlinuz and initrd to the casper directory. It is at this point that grub loads the kernel and init.

I hope this helps.
