### ISSUE TITLE
Support creating secure-boot enabled images

### ISSUE THREAD

**Issue by rgrunbla** [mvallim/live-custom-ubuntu-from-scratch#51]
Hello,

Right now, the generated images are not bootable « by default » on UEFI computers with microsoft keys, as the generated iso is not signed. Indeed, he grub-mkstandalone creates  an efi boot file that is not signed (as we don't have access to the keys to do so). Is there a way to rely on grub-shim or other signed alternative to boot the iso without to have to deal with secure boot keys, in this project ?

Thanks !

**Comment by mvallim** [comment]
> Hello,
> 
> Right now, the generated images are not bootable « by default » on UEFI computers with microsoft keys, as the generated iso is not signed. Indeed, he grub-mkstandalone creates an efi boot file that is not signed (as we don't have access to the keys to do so). Is there a way to rely on grub-shim or other signed alternative to boot the iso without to have to deal with secure boot keys, in this project ?
> 
> Thanks !

@rgrunbla,

In the new version:

![VirtualBox_from-scratch_07_09_2024_22_24_09](https://github.com/user-attachments/assets/b218d50b-7bf4-48bf-88e8-e4676904342e)

![VirtualBox_from-scratch_07_09_2024_22_24_40](https://github.com/user-attachments/assets/f8e356c9-7471-4ca9-ad5c-020adb3c90b9)

![VirtualBox_from-scratch_07_09_2024_22_25_09](https://github.com/user-attachments/assets/94631944-bf6b-400b-9874-261277cb067d)

![VirtualBox_from-scratch_07_09_2024_22_25_20](https://github.com/user-attachments/assets/5645c06d-79b2-4fe7-bb86-36c92986ac1c)

![VirtualBox_from-scratch_07_09_2024_22_25_33](https://github.com/user-attachments/assets/5bba2fbd-a1aa-4df4-a205-ce68ede3e330)

![VirtualBox_from-scratch_07_09_2024_22_25_43](https://github.com/user-attachments/assets/e4249985-0b85-436e-8f98-de69f822ac7c)

![VirtualBox_from-scratch_07_09_2024_22_25_59](https://github.com/user-attachments/assets/815d6ff3-3474-422b-9f2d-5fcacd0500aa)

![VirtualBox_from-scratch_07_09_2024_22_26_10](https://github.com/user-attachments/assets/bbda3b98-a53c-44fe-87e6-faeae4bb96c5)

![VirtualBox_from-scratch_07_09_2024_22_26_21](https://github.com/user-attachments/assets/38e6727c-28e7-47b3-995b-a68124fc1509)

![VirtualBox_from-scratch_07_09_2024_22_26_36](https://github.com/user-attachments/assets/89fb5303-bd85-428f-81cd-43533d649bfc)

![VirtualBox_from-scratch_07_09_2024_22_27_37](https://github.com/user-attachments/assets/b476d565-6cc1-4696-a642-7760ca1c5754)

All steps describe in README or use scripts.

**Comment by oldtime54** [comment]
I have found that the only way I can boot into live iso is to disable secure boot and do install. Then i go create MOK key using the mok-util and re-enable secure boot. Am I missing something?
