### ISSUE TITLE
Stuck problem when iso booting

### ISSUE THREAD

**Issue by olmezgokhan** [mvallim/live-custom-ubuntu-from-scratch#54]
**Describe the bug**
I want to create a custom iso for Ubuntu 22.04 (jammy) server.
I'm running the script in the order it should be. I am successfully creating an iso. I have not encountered any errors until this step. But after making the iso bootable and going through the installation step, the installation gets **stuck** on the screen where the services are checked.
it stays in the "dispatcher daemon for systemd-networkd" step and does not jump.

I'm opening a second teminal with ALT+F2. i uninstall the service called **neworkd** and install it again. And this time he's stuck on the next step after that. I might be doing wrong? I'll be glad if you help.

**To Reproduce**
1. ./build.sh setup_host
2. ./build.sh debootstrap
3. ./build.sh run_chroot
4. ./build.sh build_iso
5.  Use the iso

**Screenshots**
![chroot](https://user-images.githubusercontent.com/101524983/219328143-66450237-f703-48a6-b4a0-ce3a1d7357d5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 server

**Comment by jeffersoncechinel** [comment]
Same issue here. Also, in my case, to be able to build the iso I had to comment the line that copies chroot/boot/memtest86+.bin to the image because this file does not exists and hags the build process.

**Comment by jeffersoncechinel** [comment]
> **Describe the bug** I want to create a custom iso for Ubuntu 22.04 (jammy) server. I'm running the script in the order it should be. I am successfully creating an iso. I have not encountered any errors until this step. But after making the iso bootable and going through the installation step, the installation gets **stuck** on the screen where the services are checked. it stays in the "dispatcher daemon for systemd-networkd" step and does not jump.
> 
> I'm opening a second teminal with ALT+F2. i uninstall the service called **neworkd** and install it again. And this time he's stuck on the next step after that. I might be doing wrong? I'll be glad if you help.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. ./build.sh setup_host
> 2. ./build.sh debootstrap
> 3. ./build.sh run_chroot
> 4. ./build.sh build_iso
> 5. Use the iso
> 
> **Screenshots** ![chroot](https://user-images.githubusercontent.com/101524983/219328143-66450237-f703-48a6-b4a0-ce3a1d7357d5.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu 22.04.1 server

Did you manage to make it work?

**Comment by mvallim** [comment]
@olmezgokhan and @jeffersoncechinel,

Solved in latest version of how to.
