### ISSUE TITLE
Secure Boot and Nvidia Drivers Installations

### ISSUE THREAD

**Issue by qeroll** [mvallim/live-custom-ubuntu-from-scratch#58]
Hi,

Have you had any experience with creating an image which includes Nvidia drivers, or compiled drivers which require MOK enrollment?

Running with Nvidia Drivers requires secure boot, and the MOK key is enrolled during apt installation. Later the computer requires a reboot, and an enrollment from UEFI to the said key. I was wondering if that step can somehow be automated as part of the image.

Regards,

**Comment by Anduin2017** [comment]
I also had the same issue. Tried #62 and I believe this should be working.

**Comment by mvallim** [comment]
Related in #51
