### ISSUE TITLE
ubuntu 20 not installing 

### ISSUE THREAD

**Issue by adamkrawczyk** [mvallim/live-custom-ubuntu-from-scratch#6]
Hi, I have a problem with ubuntu20 - it's not installing. 
I'm using a re-made script that was working for ubuntu18. Under ubuntu20 I got no errors during fast check, got a normal boot menu, but the system goes to live boot instead of installation. 

I'm using the following command:

```
menuentry "Install Ubuntu 20.04" {
    linux /casper/vmlinuz boot=casper automatic-ubiquity hostname=user debian-installer/locale=en_GB console-setup/layoutcode=us auto=true quiet splash ---
    initrd /casper/initrd
}
```
Where should I look for errors or why this may happen. When the system is up all packages I've installed are properly installed and the kernel is appropriate. I'm trying this with a virtual-box machine for ubuntu-x64.

**Comment by mvallim** [comment]
Hi @adamkrawczyk,

I'm trying to reproduce this problem that you reported, but I'm not getting it.

I'm using this current documentation from git which is an update to Ubuntu 20 (focal).

The documentation for the other versions can be found here:

- Ubuntu 20 -focal - https://github.com/mvallim/live-custom-ubuntu-from-scratch/releases/tag/focal
- Ubuntu 18 - bionic - https://github.com/mvallim/live-custom-ubuntu-from-scratch/releases/tag/bionic

Would you have more details about the problem?

I redid all the steps and executed the installation as well as the live boot.

Thanks,

**Comment by adamkrawczyk** [comment]
Hi, 

Sorry, I didn't post an update, but I made this works. 

Here is what I got wrong. 

1. Missing grub-mkstandalone install 

```
grub-mkstandalone \
    --format=x86_64-efi \
    --output=$ROOT_DIR/image/isolinux/bootx64.efi \
    --locale-directory="$ROOT_DIR/rootfs/usr/share/locale" \
    --locales="" \
    --fonts="" \
    "boot/grub/grub.cfg=isolinux/grub.cfg" \
--directory=$ROOT_DIR/rootfs/usr/lib/grub/x86_64-efi/
```

```
grub-mkstandalone \
    --format=x86_64-efi \
    --output=$ROOT_DIR/image/isolinux/bootx64.efi \
    --install-modules="linux normal iso9660 memdisk search tar ls linuxefi" \
    --modules="linux normal iso9660 memdisk search tar ls linuxefi" \
    --locale-directory="$ROOT_DIR/rootfs/usr/share/locale" \
    --locales="" \
    --fonts="" \
    "boot/grub/grub.cfg=isolinux/grub.cfg" \
--directory=$ROOT_DIR/rootfs/usr/lib/grub/x86_64-efi/
```

Now this works. So this was my fault. 

Thank you for your time.

Best,
Adam

**Comment by mvallim** [comment]
Hi @adamkrawczyk,

No problem.

Thank you for your feedback.
