### ISSUE TITLE
QUESTION : Please inform the environtment in major step

### ISSUE THREAD

**Issue by ChristoferRian** [mvallim/live-custom-ubuntu-from-scratch#68]
as a person who does not speak native English, i had a pretty struggle to know in what environtment the code in "step-by-step".
as much i understanding (and please correct me if i'm wrong and please inform me too), it should be like this right(?)  : 
1. Prerequisites (GNU/Linux Ubuntu) - Build System
2. Bootstrap and Configure Ubuntu - Build System
3. Define chroot environment - Live System
4. Create the CD image directory and populate it - Build System
5. GRUB menu configuration - Build System
6. Create manifest - Build System
7. Create diskdefines - Build System
8. Creating the certificates to Secure Boot - Build System
9. Creating image - Build System
10. Cleanup the chroot environment - Live System
11. Unbind mount points - Build System
12. Compress the chroot - Build System

**Comment by mvallim** [comment]
> as a person who does not speak native English, i had a pretty struggle to know in what environtment the code in "step-by-step". as much i understanding (and please correct me if i'm wrong and please inform me too), it should be like this right(?) :
> 
> 1. Prerequisites (GNU/Linux Ubuntu) - Build System
> 2. Bootstrap and Configure Ubuntu - Build System
> 3. Define chroot environment - Live System
> 4. Create the CD image directory and populate it - Build System
> 5. GRUB menu configuration - Build System
> 6. Create manifest - Build System
> 7. Create diskdefines - Build System
> 8. Creating the certificates to Secure Boot - Build System
> 9. Creating image - Build System
> 10. Cleanup the chroot environment - Live System
> 11. Unbind mount points - Build System
> 12. Compress the chroot - Build System

@ChristoferRian,

The major steps:

1. Prerequisites (GNU/Linux Ubuntu)
2. Bootstrap and Configure Ubuntu
3. Define chroot environment
4. Create the CD image directory and populate it
5. GRUB menu configuration
6. Create manifest
7. Create diskdefines
8. Creating the certificates to Secure Boot
9. Creating image
10. Cleanup the chroot environment
11. Unbind mount points
12. Compress the chroot
13. Create ISO Image for a LiveCD (BIOS + UEFI + Secure Boot)
