### ISSUE TITLE
Is there bash script file for this process?

### ISSUE THREAD

**Issue by monkey-jsun** [mvallim/live-custom-ubuntu-from-scratch#8]
First of all, this document is amazingly clear and technically superb!  My hats-off!  I followed the instructions once and it worked like a charm.

The commands are so deterministic.  I just wonder if you have a bash script hiding behind.  If so, I think we all appreciate if you can share it.  Many of us are looking for recipes to create our own customized livecd, and yours could be base for them.

Thanks again.

**Comment by monkey-jsun** [comment]
For whatever it is worth -  I have developed a script that is pretty faithful to this document (Thanks.  It is a great doc!).  Anyone reaching here might find my script useful.  Of course, you should take away my customization part which is easily identifiable.   BTW, my project is to run Electrum bitcoin wallet on a USB drive.

https://github.com/monkey-jsun/eroas

**Comment by mvallim** [comment]
Hi @monkey-jsun,

You could contribute to this repo with the script without customization, creating a PR.

What do you think of the idea?

Best regards,
Vallim

**Comment by monkey-jsun** [comment]
Sounds good.  I will do that shortly.

**Comment by mvallim** [comment]
Hi @monkey-jsun,

Thanks for your great contribution!

**Comment by fcore117** [comment]
Thank you both for keeping this maintained, it is good to build barebone Ubuntu desktop without any extra cruft like languages, fonts, narrator and much more. Ubuntu official minimal installation still leaves lot of unneeded things behind.
